### ISSUE TITLE
goneovim panics on startup (when minimap is disabled?)

### ISSUE THREAD

**Issue by urandom** [akiyosi/goneovim#209]
Judging by the message, it seems that the code always expects the minimap to be enabled

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xe0e41c]

goroutine 1 [running, locked to thread]:
github.com/akiyosi/goneovim/editor.(*Workspace).lazyDrawUI(0xc000404700)
	github.com/akiyosi/goneovim/editor/workspace.go:267 +0xac
github.com/akiyosi/goneovim/editor.(*Workspace).registerSignal.func3()
	github.com/akiyosi/goneovim/editor/workspace.go:374 +0x3e
github.com/akiyosi/goneovim/editor.callbackworkspaceSignal28652a_LazyDrawSignal(0x3a2b470)
	github.com/akiyosi/goneovim/editor/moc.go:419 +0x68
github.com/akiyosi/goneovim/editor._cgoexpwrap_45da67de0cd5_callbackworkspaceSignal28652a_LazyDrawSignal(0x3a2b470)
	_cgo_gotypes.go:4540 +0x2b
github.com/akiyosi/goneovim/editor._Cfunc_workspaceSignal28652a_EventDefault(0x3a2b470, 0x7fca7c000c40, 0x0)
	_cgo_gotypes.go:4029 +0x4a
github.com/akiyosi/goneovim/editor.(*workspaceSignal).EventDefault.func1(0xc00043e050, 0x1359180, 0xc00050e258, 0xc00050e258)
	github.com/akiyosi/goneovim/editor/moc.go:755 +0xb6
github.com/akiyosi/goneovim/editor.(*workspaceSignal).EventDefault(0xc00043e050, 0x1359180, 0xc00050e258, 0x5)
	github.com/akiyosi/goneovim/editor/moc.go:755 +0x4d
github.com/akiyosi/goneovim/editor.callbackworkspaceSignal28652a_Event(0x3a2b470, 0x7fca7c000c40, 0x11c1b58)
	github.com/akiyosi/goneovim/editor/moc.go:750 +0x11e
github.com/akiyosi/goneovim/editor._cgoexpwrap_45da67de0cd5_callbackworkspaceSignal28652a_Event(0x3a2b470, 0x7fca7c000c40, 0x7fca68005010)
	_cgo_gotypes.go:4644 +0x35
github.com/therecipe/qt/widgets._Cfunc_QApplication_QApplication_Exec(0xc000000000)
	_cgo_gotypes.go:2600 +0x49

```

**Comment by akiyosi** [comment]
Hi :)
Thanks for the report. 
I have tried to fix this problem.

Could you please try the latest build below?
https://github.com/akiyosi/goneovim/actions/runs/741108632

**Comment by urandom** [comment]
Hi @akiyosi 

It doesn't panic on startup with that build anymore. Though it doesn't seem to find the settings file either. I have the following under `~/.config/goneovim/settings.toml` on linux

```
StartFullscreen = true
ExtCmdline   = true
ExtPopupmenu = true
ExtTabline   = true
ExtMessages  = true
DisableLigatures = false
RestoreSession = true
```

And none of these settings appear to be active. The debug log says that the config is being read (though it doesn't specify from which path):
```
2021/04/12 17:16:30.739312 000.639 reading config
```

**Comment by akiyosi** [comment]
Hi, thanks for the confirmation.

Would it behave differently if you set it as follows?

```
[Editor]
StartFullscreen = true
ExtCmdline   = true
ExtPopupmenu = true
ExtTabline   = true
ExtMessages  = true
DisableLigatures = false

[Workspace]
RestoreSession = true
```

**Comment by urandom** [comment]
@akiyosi 

Yep, was missing the headers. I guess I didn't see them since they were commented out in the wiki page.

**Comment by akiyosi** [comment]
@urandom 
Oh, sorry. I have fixed wiki page.
