### ISSUE TITLE
Goneovim crashes when minimap is disabled

### ISSUE THREAD

**Issue by cheap-glitch** [akiyosi/goneovim#230]
Goneovim immediately crashes on my system when disabling the Minimap feature.

### Steps to reproduce

1. Create a config file with the following contents:
```toml
[MiniMap]
Disable = true
```
2. Run `goneovim`

<details>
<summary>Output</summary>

```text
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xe0e41c]

goroutine 1 [running, locked to thread]:
github.com/akiyosi/goneovim/editor.(*Workspace).lazyDrawUI(0xc000410000)
	github.com/akiyosi/goneovim/editor/workspace.go:267 +0xac
github.com/akiyosi/goneovim/editor.(*Workspace).registerSignal.func3()
	github.com/akiyosi/goneovim/editor/workspace.go:374 +0x3e
github.com/akiyosi/goneovim/editor.callbackworkspaceSignal28652a_LazyDrawSignal(0x2a7a4e0)
	github.com/akiyosi/goneovim/editor/moc.go:419 +0x68
github.com/akiyosi/goneovim/editor._cgoexpwrap_45da67de0cd5_callbackworkspaceSignal28652a_LazyDrawSignal(0x2a7a4e0)
	_cgo_gotypes.go:4540 +0x2b
github.com/akiyosi/goneovim/editor._Cfunc_workspaceSignal28652a_EventDefault(0x2a7a4e0, 0x7f6fd8000c40, 0x0)
	_cgo_gotypes.go:4029 +0x4a
github.com/akiyosi/goneovim/editor.(*workspaceSignal).EventDefault.func1(0xc0003be050, 0x1359180, 0xc000010008, 0xc000010008)
	github.com/akiyosi/goneovim/editor/moc.go:755 +0xb6
github.com/akiyosi/goneovim/editor.(*workspaceSignal).EventDefault(0xc0003be050, 0x1359180, 0xc000010008, 0x5)
	github.com/akiyosi/goneovim/editor/moc.go:755 +0x4d
github.com/akiyosi/goneovim/editor.callbackworkspaceSignal28652a_Event(0x2a7a4e0, 0x7f6fd8000c40, 0x11c1b58)
	github.com/akiyosi/goneovim/editor/moc.go:750 +0x11e
github.com/akiyosi/goneovim/editor._cgoexpwrap_45da67de0cd5_callbackworkspaceSignal28652a_Event(0x2a7a4e0, 0x7f6fd8000c40, 0x1)
	_cgo_gotypes.go:4644 +0x35
github.com/therecipe/qt/widgets._Cfunc_QApplication_QApplication_Exec(0xc000000000)
	_cgo_gotypes.go:2600 +0x49
github.com/therecipe/qt/widgets.QApplication_Exec(...)
	github.com/therecipe/qt/widgets/widgets-minimal.go:2983
github.com/akiyosi/goneovim/editor.InitEditor(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	github.com/akiyosi/goneovim/editor/editor.go:341 +0xe5e
main.main()
	github.com/akiyosi/goneovim/cmd/goneovim/main.go:30 +0xa3
```
</details>

### Extra infos
System: Arch Linux
Compositor: Sway (Wayland)
Goneovim version: 0.4.11

**Comment by akiyosi** [comment]
Hi,
Thanks for reporting this issue :)

I believe this is a known issue and is fixed in the latest build of master.
Please try the following latest build of GHA.

https://github.com/akiyosi/goneovim/actions/runs/911099151

**Comment by cheap-glitch** [comment]
Indeed the bug is gone in this build. Thanks for the quick reply!

**Comment by cheap-glitch** [comment]
Hi,
do you plan on making a release soon? I've noticed several other annoying bugs & crashes in 0.4.11 that seem to have been fixed since. But users like me who installed goneovim via a package manager can't benefit from those fixes if they're not under a proper release tag.

**Comment by akiyosi** [comment]
Hi, 
Sorry for the delay in release.
I have a recent release planned, but in the meantime I am working on analyzing some of the most recent issues (#231,#237,#238). 
If any of these issues contain critical bugs in Goneovim, I would like to fix them before releasing.
