### ISSUE TITLE
Crash on pressing ` key (U+0060)

### ISSUE THREAD

**Issue by colinux** [akiyosi/goneovim#290]
Hi,

on macOS, app instantly crash when pressing ` key (U+0060), in normal & insert modes.
(There is a dedicated key on french keyboards.)
I'm pretty sure this is a recent regression.

```
› /Applications/goneovim.app/Contents/MacOS/goneovim -u NONE

(editor start, I'm pressing `)

 panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0x42832e9]

goroutine 1 [running, locked to thread]:
github.com/akiyosi/goneovim/editor.(*Tooltip).update(0xc000024280)
	github.com/akiyosi/goneovim/editor/tooltip.go:120 +0x49
github.com/akiyosi/goneovim/editor.(*Workspace).InputMethodEvent(0xc000014600, 0xc0004c4440)
	github.com/akiyosi/goneovim/editor/workspace.go:2423 +0x205
github.com/therecipe/qt/widgets.callbackQWidget_InputMethodEvent(0x600000c1cba0, 0x208c03730)
	github.com/therecipe/qt/widgets/widgets-minimal.go:21985 +0x9d
github.com/therecipe/qt/widgets._Cfunc_QWidget_EventDefault(0x600000c1cba0, 0x208c03730, 0x0)
	_cgo_gotypes.go:16363 +0x45
github.com/therecipe/qt/widgets.(*QWidget).EventDefault.func1(0xc000119328, 0x4575a08, 0xc0004c4438, 0xc0004c4438)
	github.com/therecipe/qt/widgets/widgets-minimal.go:21536 +0xa5
github.com/therecipe/qt/widgets.(*QWidget).EventDefault(0xc000119328, 0x4575a08, 0xc0004c4438, 0x5)
	github.com/therecipe/qt/widgets/widgets-minimal.go:21536 +0x4d
github.com/therecipe/qt/widgets.callbackQWidget_Event(0x600000c1cba0, 0x208c03730, 0x4008a1b)
	github.com/therecipe/qt/widgets/widgets-minimal.go:21502 +0x125
github.com/therecipe/qt/widgets._Cfunc_QApplication_QApplication_Exec(0xc000000000)
	_cgo_gotypes.go:2449 +0x45
github.com/therecipe/qt/widgets.QApplication_Exec(...)
	github.com/therecipe/qt/widgets/widgets-minimal.go:2848
github.com/akiyosi/goneovim/editor.InitEditor(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	github.com/akiyosi/goneovim/editor/editor.go:351 +0xf4a
main.main()
	github.com/akiyosi/goneovim/cmd/goneovim/main.go:53 +0x147

```

Environment : M1 with v0.4.13-13-gdbfad92 (build from fix of my previous issue https://github.com/akiyosi/goneovim/issues/284#issuecomment-976099387 )

Tell me how can I provide additional details if needed !

**Comment by akiyosi** [comment]
Hi :D 
Thanks for the report!
I am trying to fix this issue.
Could you please try the following fix?

https://github.com/akiyosi/goneovim/actions/runs/1520893074

**Comment by colinux** [comment]
Still a crash but trace is different :

```
› panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x42571dc]

goroutine 1 [running, locked to thread]:
github.com/akiyosi/goneovim/editor.(*IMETooltip).setQpainterFont(0xc0000242d0, 0xc0005fdbc0)
	github.com/akiyosi/goneovim/editor/imetooltip.go:19 +0xbc
github.com/akiyosi/goneovim/editor.(*Tooltip).drawForeground(0xc0000242d0, 0xc0005fdbc0, 0xc00011cdb8, 0xc00011cda8)
	github.com/akiyosi/goneovim/editor/tooltip.go:30 +0x48
github.com/akiyosi/goneovim/editor.(*IMETooltip).paint(0xc0000242d0, 0xc0005fdba8)
	github.com/akiyosi/goneovim/editor/imetooltip.go:46 +0x9d
github.com/akiyosi/goneovim/editor.callbackTooltip18c51e_PaintEvent(0x600000c3a580, 0x208a54d60)
	github.com/akiyosi/goneovim/editor/moc.go:3970 +0x9d
github.com/akiyosi/goneovim/editor._Cfunc_Tooltip18c51e_EventDefault(0x600000c3a580, 0x208a54d60, 0x0)
	_cgo_gotypes.go:3185 +0x45
github.com/akiyosi/goneovim/editor.(*Tooltip).EventDefault.func1(0xc0000a6d20, 0x45758c8, 0xc0005fdba0, 0xc0005fdba0)
	github.com/akiyosi/goneovim/editor/moc.go:3595 +0xa5
github.com/akiyosi/goneovim/editor.(*Tooltip).EventDefault(0xc0000a6d20, 0x45758c8, 0xc0005fdba0, 0x5)
	github.com/akiyosi/goneovim/editor/moc.go:3595 +0x4e
github.com/akiyosi/goneovim/editor.callbackTooltip18c51e_Event(0x600000c3a580, 0x208a54d60, 0x400919b)
	github.com/akiyosi/goneovim/editor/moc.go:3590 +0x125
github.com/akiyosi/goqtframelesswindow._Cfunc_QFramelessWindowf571e4_EventDefault(0x600000c30bd0, 0x600000245260, 0x0)
	_cgo_gotypes.go:390 +0x45
github.com/akiyosi/goqtframelesswindow.(*QFramelessWindow).EventDefault.func1(0xc00012c480, 0x45758c8, 0xc0005fdb90, 0xc0005fdb90)
	github.com/akiyosi/goqtframelesswindow/moc.go:504 +0xa5
github.com/akiyosi/goqtframelesswindow.(*QFramelessWindow).EventDefault(0xc00012c480, 0x45758c8, 0xc0005fdb90, 0x5)
	github.com/akiyosi/goqtframelesswindow/moc.go:504 +0x4f
github.com/akiyosi/goqtframelesswindow.callbackQFramelessWindowf571e4_Event(0x600000c30bd0, 0x600000245260, 0x400919b)
	github.com/akiyosi/goqtframelesswindow/moc.go:499 +0x125
github.com/therecipe/qt/widgets._Cfunc_QApplication_QApplication_Exec(0xc000000000)
	_cgo_gotypes.go:2449 +0x45
github.com/therecipe/qt/widgets.QApplication_Exec(...)
	github.com/therecipe/qt/widgets/widgets-minimal.go:2848
github.com/akiyosi/goneovim/editor.InitEditor(0x100, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	github.com/akiyosi/goneovim/editor/editor.go:351 +0xf4a
main.main()
	github.com/akiyosi/goneovim/cmd/goneovim/main.go:53 +0x147
```


Tried with v0.4.13-18-ge6bdd81 from link _Goneovim-latest-macos-5.15.2_  (I don't know why there is also a 5.13.0 build).

**Comment by akiyosi** [comment]
I'm sorry.
Could you please check again?
https://github.com/akiyosi/goneovim/actions/runs/1521544399

**Comment by colinux** [comment]
Yeah, it's fixed. Thanks for your reactivity ! 🚀

**Comment by akiyosi** [comment]
Oh, good!
Close.
