### ISSUE TITLE
Can't open on MacOs

### ISSUE THREAD

**Issue by Chaitanyabsprip** [akiyosi/goneovim#307]
I went through all the similar issues and couldn't find a solution.
I am using MacOS v12.1 with M1 chip and clicking on the goneovim app does nothing. so I tried to open the executable from the command line and then got the following error

```sh
open /Users/chaitanyasharma/.goneovim/setting.toml: no such file or directory
panic: runtime error: index out of range [-9223372036854775808]

goroutine 1 [running, locked to thread]:
github.com/akiyosi/goneovim/editor.(*Window).drawBackground(0xc0003ea000, 0xc000181e68, 0x0, 0x8000000000000000, 0x8000000000000000)
	github.com/akiyosi/goneovim/editor/window.go:1750 +0x5e5
github.com/akiyosi/goneovim/editor.(*Window).paint(0xc0003ea000, 0xc000181e58)
	github.com/akiyosi/goneovim/editor/window.go:222 +0x293
github.com/akiyosi/goneovim/editor.callbackWindow18c51e_PaintEvent(0x600001755d40, 0x208d33410)
	github.com/akiyosi/goneovim/editor/moc.go:5497 +0x9d
github.com/akiyosi/goneovim/editor._Cfunc_Window18c51e_EventDefault(0x600001755d40, 0x208d33410, 0x0)
	_cgo_gotypes.go:4490 +0x45
github.com/akiyosi/goneovim/editor.(*Window).EventDefault.func1(0xc0003ea000, 0x4575668, 0xc000181e50, 0xc000181e50)
	github.com/akiyosi/goneovim/editor/moc.go:5122 +0xa5
github.com/akiyosi/goneovim/editor.(*Window).EventDefault(0xc0003ea000, 0x4575668, 0xc000181e50, 0x5)
	github.com/akiyosi/goneovim/editor/moc.go:5122 +0x4f
github.com/akiyosi/goneovim/editor.callbackWindow18c51e_Event(0x600001755d40, 0x208d33410, 0x400967b)
	github.com/akiyosi/goneovim/editor/moc.go:5117 +0x125
github.com/therecipe/qt/widgets._Cfunc_QApplication_QApplication_Exec(0xc000000000)
	_cgo_gotypes.go:2449 +0x45
github.com/therecipe/qt/widgets.QApplication_Exec(...)
	github.com/therecipe/qt/widgets/widgets-minimal.go:2848
github.com/akiyosi/goneovim/editor.InitEditor(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	github.com/akiyosi/goneovim/editor/editor.go:345 +0xf3d
main.main()
	github.com/akiyosi/goneovim/cmd/goneovim/main.go:53 +0x147
```

**Comment by akiyosi** [comment]
@Chaitanyabsprip 
Hi,
Thanks for the issue report.

Let me check a few things about your environment in order to investigate the problem.

* What is the version of nvim? The minimum nvim version that Goneovim expects is v0.6.0.
  `nvim --version`

* What is the version of Goneovim?
  `/Applications/goneovim.app/Contents/MacOS/goneovim --version`

* If you run the following from the command line, is there any change in behavior?
  `/Applications/goneovim.app/Contents/MacOS/goneovim -u NONE`
