### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by snowair** [akiyosi/goneovim#452]
MacOS 使用搜狗输入法会崩溃

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x100241723]

goroutine 1 [running, locked to thread]:
github.com/akiyosi/goneovim/editor.(*Tooltip).updateText(0xc0000a8070, 0xc00028e540, {0xc00075eb30?, 0xc0000021a0?})
        github.com/akiyosi/goneovim/editor/tooltip.go:149 +0xe3
github.com/akiyosi/goneovim/editor.(*IMETooltip).parsePreeditString(0xc0000a8070, {0xc00075eb30, 0x1})
        github.com/akiyosi/goneovim/editor/imetooltip.go:191 +0x52c
github.com/akiyosi/goneovim/editor.(*Workspace).InputMethodEvent(0xc0000bc000, 0x1?)
        github.com/akiyosi/goneovim/editor/workspace.go:2795 +0xcd
github.com/therecipe/qt/widgets.callbackQWidget_InputMethodEvent(0x600000c43090, 0x7ff7bfef8940)
        github.com/therecipe/qt/widgets/widgets-minimal.go:22101 +0x93
github.com/therecipe/qt/widgets._Cfunc_QWidget_EventDefault(0x600000c43090, 0x7ff7bfef8940)
        _cgo_gotypes.go:16519 +0x49
github.com/therecipe/qt/widgets.(*QWidget).EventDefault.func1(0x8?, {0x100512308?, 0xc0002d4818?})
        github.com/therecipe/qt/widgets/widgets-minimal.go:21652 +0x9f
github.com/therecipe/qt/widgets.(*QWidget).EventDefault(0x1003dc860?, {0x100512308?, 0xc0002d4818?})
        github.com/therecipe/qt/widgets/widgets-minimal.go:21652 +0x37
github.com/therecipe/qt/widgets.callbackQWidget_Event(0x600000c43090, 0x7ff7bfef8940)
        github.com/therecipe/qt/widgets/widgets-minimal.go:21618 +0xff
github.com/therecipe/qt/widgets._Cfunc_QApplication_QApplication_Exec()
        _cgo_gotypes.go:2493 +0x48
github.com/therecipe/qt/widgets.QApplication_Exec(...)
        github.com/therecipe/qt/widgets/widgets-minimal.go:2903
github.com/akiyosi/goneovim/editor.InitEditor({{0x0, 0x0}, {0x7ff7bfeff9dd, 0x12}, {0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, ...}, ...)
        github.com/akiyosi/goneovim/editor/editor.go:392 +0xf98
main.main()
        github.com/akiyosi/goneovim/cmd/goneovim/main.go:72 +0x231
```

**Comment by akiyosi** [comment]
Thanks for the report.
This is the same issue as #430 and has been fixed in HEAD. Please try nightly-build if you would like to try it.
