### ISSUE TITLE
Can't start: `interface {} is uint64, not nvim.Window`

### ISSUE THREAD

**Issue by amagee** [akiyosi/goneovim#82]
Using Ubuntu 18.04

- Downloaded goneovim version 0.4.1 for linux: (goneovim-0.4.1-linux.tar.bz2)
- Extracted
- Ran `./goneovim`

A window briefly appears and then disappears, and the following output appears:

```
panic: interface conversion: interface {} is uint64, not nvim.Window

goroutine 1 [running, locked to thread]:
github.com/akiyosi/goneovim/editor.(*Screen).windowPosition(0xc0001e2d00, 0xc0002e5e70, 0x1, 0x1)
        github.com/akiyosi/goneovim/editor/screen.go:2523 +0x32b
github.com/akiyosi/goneovim/editor.(*Workspace).handleRedraw(0xc000260000, 0xc0003b2000, 0x9, 0x9)
        github.com/akiyosi/goneovim/editor/workspace.go:767 +0x2cd
github.com/akiyosi/goneovim/editor.(*Workspace).registerSignal.func1()
        github.com/akiyosi/goneovim/editor/workspace.go:221 +0x7d
github.com/akiyosi/goneovim/editor.callbackworkspaceSignal28652a_RedrawSignal(0x39d8070)
        github.com/akiyosi/goneovim/editor/moc.go:1127 +0x68
github.com/akiyosi/goneovim/editor._cgoexpwrap_a074abc4c182_callbackworkspaceSignal28652a_RedrawSignal(0x39d8070)
        _cgo_gotypes.go:2208 +0x2b
github.com/akiyosi/goneovim/editor._Cfunc_workspaceSignal28652a_EventDefault(0x39d8070, 0x7f30ac0011d0, 0x0)
        _cgo_gotypes.go:1383 +0x4a
github.com/akiyosi/goneovim/editor.(*workspaceSignal).EventDefault.func1(0xc000250000, 0xe00000, 0xc000463528, 0xc000463528)
        github.com/akiyosi/goneovim/editor/moc.go:1721 +0xb6
github.com/akiyosi/goneovim/editor.(*workspaceSignal).EventDefault(0xc000250000, 0xe00000, 0xc000463528, 0x5)
        github.com/akiyosi/goneovim/editor/moc.go:1721 +0x4d
github.com/akiyosi/goneovim/editor.callbackworkspaceSignal28652a_Event(0x39d8070, 0x7f30ac0011d0, 0xd1e730)
        github.com/akiyosi/goneovim/editor/moc.go:1716 +0x11e
github.com/akiyosi/goneovim/editor._cgoexpwrap_a074abc4c182_callbackworkspaceSignal28652a_Event(0x39d8070, 0x7f30ac0011d0, 0x1)
        _cgo_gotypes.go:2390 +0x35
github.com/therecipe/qt/widgets._Cfunc_QApplication_QApplication_Exec(0xc000000000)
        _cgo_gotypes.go:2492 +0x49
github.com/therecipe/qt/widgets.QApplication_Exec(...)
        github.com/therecipe/qt/widgets/widgets-minimal.go:2860
github.com/akiyosi/goneovim/editor.InitEditor()
        github.com/akiyosi/goneovim/editor/editor.go:235 +0x780
main.main()
        github.com/akiyosi/goneovim/cmd/goneovim/main.go:14 +0x20
```

**Comment by akiyosi** [comment]
hi

goneovim expects `nvim` to be placed under `$PATH`.  
Check this point in your environment.

**Comment by amagee** [comment]
Yep, `nvim` is installed and runs successfully.

**Comment by akiyosi** [comment]
ok, what is your `nvim` version?

**Comment by amagee** [comment]
```
$ nvim --version
NVIM v0.4.0-103-g8510d5ff8
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: /usr/bin/gcc-5 -Wshadow -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/home/travis/build/neovim/bot-ci/build/neovim/build/config -I/home/travis/build/neovim/bot-ci/build/neovim/src -I/home/travis/build/neovim/bot-ci/build/neovim/.deps/usr/include -I/usr/include -I/home/travis/build/neovim/bot-ci/build/neovim/build/src/nvim/auto -I/home/travis/build/neovim/bot-ci/build/neovim/build/include
Compiled by travis@travis-job-26c16eea-d977-4c01-9a4f-a71736eac8d8

Features: +acl +iconv +jemalloc +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/home/travis/build/neovim/bot-ci/build/neovim/build/nvim.AppDir/usr/share/nvim
```

**Comment by akiyosi** [comment]
thx.

goneovim expects nvim version v0.4.2 or later.  Please deploy the latest nvim and run again to check.

**Comment by amagee** [comment]
Oh cool, that works, thanks :)
